### ISSUE TITLE
Extension not working on Yarn Start 

### ISSUE THREAD

**Issue by SamFrampton01** [satendra02/react-chrome-extension#44]
Cloned the repo and have the same manifest.json file and package.json and my Node Version is `v14.11.0`

I receive the following error when running yarn start and cannot open the popup after uploading build folder to the chrome store. Can you help me understand why it's not working?

```
{
  "name": "my-extension",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/runtime": "^7.10.4",
    "autoprefixer": "^9.8.5",
    "case-sensitive-paths-webpack-plugin": "^2.3.0",
    "chalk": "^4.1.0",
    "css-loader": "^3.6.0",
    "dotenv": "^8.2.0",
    "dotenv-expand": "^5.1.0",
    "fs-extra": "^9.0.1",
    "postcss-flexbugs-fixes": "^4.2.1",
    "promise": "8.0.1",
    "prop-types": "^15.7.2",
    "raf": "3.4.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-frame-component": "^4.1.2",
    "resolve": "^1.17.0",
    "whatwg-fetch": "3.2.0"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom",
    "watch": "npm-watch"
  },
  "watch": {
    "build": {
        "patterns": [
            "src",
            "public"
        ],
        "extensions": "js,html,css,json,svg"
    }
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node",
      "mjs"
    ]
  },
  "babel": {
    "presets": [
      "react-app",
      "@babel/preset-env",
      "@babel/preset-react"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "devDependencies": {
    "@babel/core": "^7.10.4",
    "@babel/preset-env": "^7.10.4",
    "@babel/preset-react": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.10.4",
    "@typescript-eslint/eslint-plugin": "^3.6.0",
    "@typescript-eslint/parser": "^3.6.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.1.0",
    "babel-loader": "^8.1.0",
    "babel-preset-react-app": "^9.1.2",
    "eslint": "^7.4.0",
    "eslint-config-react-app": "^5.2.1",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-flowtype": "^5.2.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.20.3",
    "eslint-plugin-react-hooks": "^4.0.7",
    "file-loader": "^6.0.0",
    "html-webpack-plugin": "^4.3.0",
    "jest": "^26.1.0",
    "mini-css-extract-plugin": "^0.9.0",
    "npm-watch": "^0.6.0",
    "postcss-loader": "^3.0.0",
    "react-dev-utils": "^10.2.1",
    "style-loader": "^1.2.1",
    "sw-precache-webpack-plugin": "^1.0.0",
    "url-loader": "^4.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0",
    "webpack-manifest-plugin": "^2.2.0"
  }
}
```

 

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/express/lib/router/index.js:317:13)
    at /Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/samframpton/Documents/code/outflow/react-chrome-extension/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by satendra02** [comment]
Hey @SamFrampton01 

Sorry for the late reply I was really busy last week. 

Thanks for reporting the issue. Created PR #45 to fix this issue. Let me know if this solves your issue, I will then merge this to master.

**Comment by SamFrampton01** [comment]
Hey @satendra02 the updates to webpack.config.js have fixed the problem.

**Comment by satendra02** [comment]
Great 👍
